site_name: Proyecto intermodular
site_url: https://joperpu.github.io/pi2526
theme:
  name: material
  language: es
  favicon: assets/images/logo.ico
  features:
    - content.code.copy
  palette: 
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: "assets/images/logo.png"
nav:
  - Página principal: index.md
  - Introducción a la metodología de proyectos: intro.md
  - Proyecto 1:
    - Proyecto 1 Parte 1: pr1.1.md
    - Proyecto 1 Parte 2: pr1.2.md
  - Proyecto 2:
    - Proyecto 2: pr2.md
    - Plantilla memoria P2: plantilla_memoria_p2.md
  - Proyecto 3:
    - Proyecto 3: pr3.md
    - Ayuda técnica: pr3hlp.md
  - Docker:
    - Taller de Docker: https://aulasoftwarelibre.github.io/taller-de-docker/
  - Proyecto final:
    - Anteproyecto: anteproyecto.md
    - Proyecto final: proyecto.md

copyright: "2026 José María Pérez Puentes - Licencia CC BY-NC-SA 4.0"

extra:
  generator: true

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - admonition
  - pymdownx.details